services:
  - type: web
    name: sqlbackup-monitor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sqlbackup-db
          property: connectionString
      - key: API_KEY
        generateValue: false   # definir manualmente no painel do Render

databases:
  - name: sqlbackup-db
    plan: free
